spring:
  application:
    name: rainmind

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME:rainmind}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  flyway:
    enabled: true
    locations: classpath:db/migration

security:
  jwt:
    secret: ${JWT_SECRET}
    access-token-exp-ms: ${JWT_ACCESS_TOKEN_EXP_MS:6000000}

kma:
  auth-key: ${KMA_AUTH_KEY}

logging:
  level:
    org.springframework.security: DEBUG