global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "rainmind-app"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["app:8080"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "redis-exporter"
    static_configs:
      - targets: ["redis_exporter:9121"]
